project:
  type: website
  output-dir: docs

website:
  title: "EuroBroadMap"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    logo: img/logo_geocites.jpg
    contents:
      - href: index.qmd
        text: "A propos"
      - section: "L'ENQUETE EBM 2009-2010"
        contents:  
          - href: Data001.qmd
            text: "Questionnaire"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/eurobroadmap
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, FR CIST
format:
  html:
    grid:
      sidebar-width: 300px
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


